# pacote
library(ggplot2)
library(readr)

# planilha
dados <- read_delim("C:/Users/natal/OneDrive/coisas 2/eventos_naicon.csv", 
                             delim = ";", escape_double = FALSE, trim_ws = TRUE)
head(dados)

# ordernar o eixo y

ordem <- c("Usos e Abusos dos Livros Didáticos e Paradidáticos",
           "Textos Didáticos",
           "Teorias e Métodos de Ensino-Aprendizagem",
           "Tempo e História",
           "Tempo e Ensino de História",
           "Temas sensíveis e afetos no Ensino de História: pensando articulações possíveis",
           "Saberes Docentes e Saberes Escolares",
           "Representações e Usos Sociais da História",
           "Relação Universidade/Escolas",
           "Reflexões sobre Aprendizagens e Sensibilidades",
           "Recursos auxiliares ao ensino",
           "Propostas de Trabalho para as 5ª e 8ª Séries",
           "Projetos Institucionais",
           "Produção e Transmissão do Conhecimento Histórico",
           "Produção do Conhecimento Histórico",
           "Produção do Conhecimento e Ensino de História",
           "Produção de Conhecimento",
           "Práticas Educativas",
           "Práticas de Memórias em Espaços Educativos",
           "Práticas de Memória e Ensino de História",
           "Povos Indígenas e o Ensino de História",
           "Políticas Sociais e Ensino de História",
           "Políticas Públicas e a Pesquisa em Ensino de História",
           "Política e Ensino de História",
           "Patrimônio e Museus nas Pesquisas em Ensino de História",
           "Parâmetros Curriculares Nacionais",
           "Os Usos do Passado & Didática da História",
           "Os Museus e a Formação da Consciência Histórica",
           "Os Docentes frente à Cultura Escolar",
           "Os Desafios da História Local",
           "Objetivos do Ensino de História",
           "O Uso Escolar das Fontes Históricas",
           "O uso das fontes no ensino de História em tempos de adaptações curriculares",
           "O Ensino de História na Encruzilhada: Desafios às Possibilidades",
           "O Ensino de História e Currículo",
           "O Ensino de História da América",
           "Novas Tecnologias, Linguagens e Ensino de História",
           "Novas Tecnologias",
           "Novas Linguagens no Ensino de História",
           "No Ensino da História, Partidarismo versus Objetividade",
           "Narrativas e produções de saberes históricos: partilhas sobre práticas, sentidos e sensibilidades em percursos educativos",
           "Narrativas e Leituras no Ensino de História",
           "Música e Ensino de História",
           "Metodologia de Ensino",
           "Memórias Sensíveis em Tempos de Guerras de Memórias",
           "Memória, Tempo e História",
           "Memória, Patrimônio e Ensino de História",
           "Memória, Fontes Orais e Ensino de História",
           "Memória e Ensino de História",
           "Materiais Didáticos e Metodologia",
           "Materiais Didáticos e Ensino de História",
           "Manuais e outros recursos didáticos: relações que constituem as diferentes culturas escolares",
           "Livros Didáticos e Paradidáticos",
           "Livros Didáticos de História",
           "Livro Didático: Uma Abordagem Plural",
           "Livro Didático",
           "Linguagens, Tecnologias e Ensino de História",
           "Linguagens e Relatos de Experiências",
           "Linguagens e Ensino de História",
           "Linguagens alternativas e novas tecnologias",
           "Linguagens Alternativas do Ensino de História",
           "Linguagens alternativas",
           "Linguagem, Cultura e Cognição",
           "Leitura de Textos Históricos Escolares",
           "Jogos, imaginação e aprendizagens",
           "Interfaces entre Currículo, Avaliação e Formação de Professores no Ensino de História",
           "Imagens, Cinema, TV e Ensino de História",
           "Identidades Culturais e Memórias Locais",
           "Historiografia, História da Educação e do Ensino",
           "Histórias e Memórias do Ensino de História",
           "Histórias e Cultura Africana, Afro-Brasileira e Indígena",
           "Histórias de vida, ensino e aprendizagem na Educação Básica: desafios e potencialidades",
           "História, Linguagens e Livros Didáticos",
           "História Social e Ensino",
           "História Pública, Mídias e Linguagens Culturais",
           "História no Ensino Fundamental e Médio",
           "História Local, Regional e Ensino de História",
           "História Local e Ensino de História",
           "História Indígena no Ensino Regular",
           "História e Memórias de Professores de História",
           "História e Memória em Espaços Escolares e Não Escolares",
           "História e Historiografia do Ensino de História",
           "História do Ensino de História e Educação",
           "História do Ensino de História",
           "História Digital e Formação Histórica em espaços educacionais escolares e não escolares",
           "História Digital e Formação Histórica",
           "História da História Ensinada",
           "História da América",
           "Gênero e Ensino de História",
           "Fronteiras Interdisciplinares no Ensino de História",
           "Formas do Conhecimento Histórico na Sala de Aula",
           "Formação do Professor/Produção do Conhecimento Histórico",
           "Formação de Professores e Ensino de História",
           "Formação de Professores e Currículo de História",
           "Formação de Professores",
           "Fontes para o Ensino da História e Cultura Africana, Afro-Brasileira e Indígena",
           "Experiências educacionais no ensino de História: documentos históricos, memória, educação patrimonial e currículos multiculturais",
           "Experiências de História Local para um Ensino de História Pluriepistêmico",
           "Estágio de Prática de Ensino",
           "Entre Práticas e Reflexões: História Pública e Ensino História",
           "Ensino-Aprendizagem",
           "Ensino, Aprendizagem e Processos Avaliativos",
           "Ensino de História: Formação de Professores e Saberes Históricos Escolares",
           "Ensino de História, Museus e Patrimônio",
           "Ensino de História, Metodologias e Projetos de Intervenção",
           "Ensino de História, linguagens e narrativas",
           "Ensino de História, Cultura, Diversidade e Alteridade",
           "Ensino de História, Cultura e Diversidade",
           "Ensino de História, Cinema e Literatura",
           "Ensino de História Regional",
           "Ensino de História no Terceiro Grau",
           "Ensino de História no Segundo Grau",
           "Ensino de História nas Américas",
           "Ensino de História na 1ª fase do Ensino Fundamental",
           "Ensino de História Local e Regional",
           "Ensino de História indígena",
           "Ensino de História em Tempos de Crise",
           "Ensino de História e suas Linguagens",
           "Ensino de História e Sociedade da Informação",
           "Ensino de História e Patrimônio Cultural: possibilidades didáticas",
           "Ensino de História e Patrimônio",
           "Ensino de História e Materiais Didáticos",
           "Ensino de História e Linguagens Artísticas: entre propostas e práticas",
           "Ensino de História e Linguagem",
           "Ensino de História e Juventude",
           "Ensino de História e Identidade e Alteridade",
           "Ensino de História e História Pública: desafios para formação do pensamento histórico na Educação Básica e no Ensino Superior",
           "Ensino de História e História Pública em tempos de negacionismos: passados em disputa",
           "Ensino de História e Formação de Professores",
           "Ensino de História e Fontes Documentais",
           "Ensino de História e Educação Étnico-Racial",
           "Ensino de História e Educação Democrática",
           "Ensino de História e Educação de Jovens e Adultos",
           "Ensino de História e Diversidades Étnico-Culturais",
           "Ensino de História e Diversidade Cultural",
           "Ensino de História e Cultura Material",
           "Ensino de História e Conhecimento Profissional Docente",
           "Ensino de História das Américas",
           "Educação Inclusiva e Ensino de História",
           "Educação Histórica nas Séries Iniciais",
           "Educação Histórica e Aprendizagens em História",
           "Educação Histórica",
           "Educação democrática e ensino de História: disputa de projetos políticos e pedagógicos, experiências e trajetórias recentes, resistências, conflitos e insurgências",
           "Documentos Escritos e Práticas de Leitura",
           "Diversidade Étnico-Racial e Ensino de História",
           "Diversidade de Linguagens e Práticas em Sala de Aula",
           "Didática e Currículo na Pesquisa em Ensino de História",
           "Didática e Aprendizagem da História",
           "Diálogo entre Diferentes Saberes e Práticas",
           "Desaprender e reaprender no ensino de história: a investigação da prática do(a) professor(a) como processo metaformativo – projetos, produtos e narrativas.",
           "Desafios Teórico-Metodológicos da Pesquisa em Ensino de História",
           "Democracia em Xeque: Temas Sensíveis e Reformas Curriculares",
           "Demandas Sociais e a Pesquisa em Ensino de História",
           "Decolonialidades e Ensino de História: práticas, memórias e experiências",
           "Currículos, Saberes e Práticas Educativas",
           "Currículos, Políticas Públicas e Ensino de História",
           "Currículos e Ensino da História",
           "Currículos de História",
           "Currículo e Práticas Pedagógicas",
           "Currículo e Práticas Escolares",
           "Currículo e Ensino",
           "Currículo",
           "Cultura Escolar e Saberes",
           "Comunidades Tradicionais: Desafios para a Educação",
           "Comunidades Tradicionais, Práticas Interculturais e Ensino de História",
           "Cartografia(s) da(s) Memória(s) Sensíveis na/da Cidade(s)",
           "Biografias, memórias das populações negras e TDIC: possibilidades e estratégias para o ensino de história",
           "Avaliação das aprendizagens no Ensino de História",
           "Audiovisuais: o cinema e o documentário no Ensino de História, reflexões para o ensino e a pesquisa",
           "As Atuais Políticas Públicas de Formação Docente",
           "Arquivos, Museus e Ensino de História",
           "Aprendizagem, Metodologia do Ensino e Avaliação em Temas Controversos",
           "Aprendizagem Histórica em tempos de pandemia: limites e possibilidades",
           "Aprendizagem Histórica em Ambiente de Escolarização",
           "Aprendizagem em História",
           "Aprendizagem e formação da  consciência histórica: experiências e reflexões sobre os conteúdos  escolares",
           "Aprendizagem da História",
           "Aprender História no Século XXI",
           "Ameaças à Educação Democrática e ao Ensino de História",
           "A Temática Indígena no Ensino de História",
           "A Produção Historiográfica e o Livro Didático",
           "A História Repensa seus Sujeitos",
           "A Constituição do Saber Histórico Escolar",
           "A Abordagem dos 'Passados Dolorosos' nos Livros Didáticos",
           "Aprendizagem Histórica e Docência: travessias formativas, saberes profissionais e experiências didático-históricas"
)

# gráfico
ggplot(dados, aes(x = factor(ano), y = factor(tema, levels = ordem))) +
  geom_point(
    aes(size = contagem, color = evento),
    alpha = 0.7,
    position = position_dodge(width = 0)
  ) +
  scale_x_discrete(expand = c(0.02, 0.02)) +
  scale_size_continuous(
    range = c(3, 10),
    name = "Tamanho das Bolhas"  # Nome da legenda de tamanho
  ) +
  scale_color_manual(
    values = c("Perspectivas" = "#1f77b4", "ENPEH" = "#ff7f0e"),
    name = "Anais"  # Nome da legenda de cores
  ) +
  labs(x = "Ano", y = "Tema") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom",  # Posiciona todas as legendas na parte inferior
    legend.box = "horizontal",   # Organiza as legendas horizontalmente
    legend.justification = c(0, 1),  # Alinha as legendas à esquerda (0) e direita (1)
    legend.spacing.x = unit(1, "cm")  # Espaço entre as legendas (ajuste conforme necessário)
  ) +
  guides(
    color = guide_legend(order = 1),  # Ordena a legenda de cores primeiro
    size = guide_legend(order = 2)    # Ordena a legenda de tamanho depois
  )


dev.copy(jpeg,'Grafico_2.png', width=20, height=25, units="in", res=500)
dev.off()
